# Generated by Django 4.0.3 on 2022-07-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cartnumber',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
