# Generated by Django 4.0.3 on 2022-07-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_cart_cartnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cartnumber',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cart',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
