# Generated by Django 4.0.3 on 2022-07-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_alter_cart_cartnumber_alter_cart_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
