# Generated by Django 4.0.3 on 2022-07-24 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_alter_cart_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cartnumber',
            new_name='items',
        ),
    ]
